config/routes.rb
Rails.application.routes.draw do
    resources :users do
        resources :chats do
            resources :messages
        end
        resources :friends
    end
    root "users#index"
end

app/models/chat.rb
class Chat < ActiveRecord::Base
    belongs_to :user
    has_many :messages
    validates :send_to_ID,presence:true
end

app/models/friend.rb
class Friend < ActiveRecord::Base
    belongs_to :user
    validates :friend_id,presence:true
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :chat
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :friends
    has_many :chats
    validates :name,presence:{ message: "ユーザー名が未入力です"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
    def create
        @user=User.find(params[:user_id])
        chat=@user.chats.find_by(send_to_ID: params[:chat].permit(:send_to_ID)[:send_to_ID] )
        if chat==nil
            @chat=@user.chats.create(send_to_ID: params[:chat].permit(:send_to_ID)[:send_to_ID] )
            redirect_to user_chat_path(@user.id,@chat.id)
        else
            @chat=chat
            redirect_to user_chat_path(@user.id,@chat.id)
        end
    end
    def destroy
        @user=User.find(params[:user_id])
        @chat=@user.chats.find(params[:id])
        @user2=User.find(@chat.send_to_ID)
        @chat2=@user2.chats.find_by(send_to_ID: @user.id)
        @chat.messages.each do |message|
            message.destroy
        end
        @chat2.messages.each do |message|
            message.destroy
        end
        @chat.destroy
        @chat2.destroy
        redirect_to user_path(params[:user_id])
    end

    def new
        @user=User.find(params[:user_id])
    end
    def show
        @user=User.find(params[:user_id])
        @chat=@user.chats.find(params[:id])
        @user2=User.find(@chat.send_to_ID)
        if @user2.chats.find_by(send_to_ID: @user.id)==nil
            @chat2=@user2.chats.create(send_to_ID: @user.id)
            @user2.friends.create(friend_id: @user.id)
        else
        @chat2=@user2.chats.find_by(send_to_ID: @user.id)
        end
        @chat2.messages.each do |message|
            message.read = true
            message.save
        end
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    def new
        @user=User.find(params[:user_id])
    end
    def create
        @user=User.find(params[:user_id])
        @friend=@user.friends.create(friend_id: params[:friend].permit(:friend_id)[:friend_id])
        redirect_to user_path(params[:user_id])
    end
    def destroy
        @friend=Friend.find(params[:id])
        @friend.destroy
        redirect_to user_path(params[:user_id])
    end
    def show
        @friend=Friend.find(params[:id])
        @user=User.find(params[:user_id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        @user=User.find(params[:user_id])
        @chat=@user.chats.find(params[:chat_id])
        @message=@chat.messages.create(text: params[:message].permit(:text)[:text])
        redirect_to user_chat_path(params[:user_id],params[:chat_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users=User.all
    end

    def show
        @user=User.find(params[:id])
    end

    def new
        @user=User.new
    end

    def create
        @user=User.new(set_user)
        if @user.save
            redirect_to users_path
        else
            render 'new'
        end
    end

    def edit
        @user=User.find(params[:id])
    end

    def update
        @user=User.find(params[:id])
        if @user.update(set_user)
            redirect_to user_path(@user.id)
        else
            render "edit"
        end
    end

    def destroy
        @user=User.find(params[:id])
        @user.chats.each do |chat|
            user2=User.find(chat.send_to_ID)
            chat2=user2.chats.find_by(send_to_ID: @user.id)
            chat.messages.each do |message|
                message.destroy
            end
            chat2.messages.each do |message|
                message.destroy
            end
            chat2.destroy
            chat.destroy
        end
        @user.friends.each do |friend|
            user3=User.find(friend.friend_id)
            friend2=user3.friends.find_by(friend_id: @user.id)
            friend2.destroy
            friend.destroy
        end
        @user.destroy
        redirect_to users_path
    end



    private
    def set_user
        x={name: params[:user].permit(:name)[:name] ,lineID: params[:user].permit(:lineID)[:lineID]}
        return x
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <script type="text/javascript">
        function goBottom(targetId) {
            var obj = document.getElementById(targetId);
            if(!obj) return;
            obj.scrollTop = obj.scrollHeight;
        }
        </script>
    </head>
    <body>
        <% a=[] %>
        <% @chat.messages.each do |message| %>
            <% a.push(message) %>
        <% end %>
        <% @chat2.messages.each do |message| %>
            <% a.push(message) %>
        <% end %>
        <% a.sort_by! {|message| message.created_at} %>

        <table id="talk">
            <thead>
                <th colspan="2"><%= User.find(@chat.send_to_ID).name %></th>
            </thead>
                <tbody id="gamen">
                    <% a.each do |message| %>
                        <tr>
                            <% if message.chat.user.id!=User.find(@chat.send_to_ID).id %>
                                <% if message.read == true %>
                                    <td id="read">既読</td>
                                    <% else %>
                                    <td class="blank"></td>
                                <% end %>
                                <td rowspan="2"><div class="right"><%= message.text %></div></td>
                                <% else %>
                                <td rowspan="2"><div class="left"><%= message.text %></div></td><td class="blank"></td>
                            <% end %>
                        </tr>
                        <tr>
                            <% if message.chat.user.id!=User.find(@chat.send_to_ID).id %>
                                <td id="time_right"><%= message.created_at.strftime("%H:%M")%></td>
                                <% else %>
                                <td id="time_left"><%= message.created_at.strftime("%H:%M")%></td>
                            <% end %>
                        </tr>
                    <% end %>
                </tbody>
        </table>

        <table id="send">
            <thead>

                <tr>
                    <th>
                    <% @message=@chat.messages.new  %>
                    <%= form_for @message, url: user_chat_messages_path(@user.id,@chat.id), method: :post do |f|%>
                        <%= f.text_area :text, :size=>"100x3"%> <%= f.submit "送信", id: "submit_button" %>
                    <%end%>
                    </th>
                </tr>
            </thead>
        </table>

        <p>
            <%= link_to "戻る",user_path(@chat.user.id) %>
        </p>

    </body>
    <script type="text/javascript">
        goBottom("gamen")
    </script>
</html>

app/views/friends/new.html.erb
<h1>友達を追加する</h1>

<p>
    <%= form_for [@user,@user.friends.build] do |f|%>
    <p>
        <%= f.label "友達のid" %>: <%= f.text_field :friend_id %>
    </p>
    <p>
        <%= f.submit "友達に追加"%>
    </p>
    <%end%>

</p>

app/views/friends/show.html.erb
<h1><%= User.find(@friend.friend_id).name %></h1>
lineID:<%= User.find(@friend.friend_id).lineID %>

<p>
<%= link_to "友達から削除する",user_friend_path(@friend.user_id,@friend.id),method: :delete,data: {confirm: User.find(@friend.friend_id).name+"を本当に友達から削除して良いですか？？"} %>
</p>
<p>
    <%= form_for [@user,@user.chats.build] do |f|%>
    <p>
        <%= f.hidden_field :send_to_ID ,value: @friend.friend_id %>
    </p>
    <p>
        <%= f.submit "トークを始める"%>
    </p>
    <%end%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>プロフィール編集画面</h1>

<%= form_for @user do |f|%>
<p>
    <%= f.label :ユーザー名%>:<%= f.text_field :name%><br>
    <%if @user.errors.any? %>
    <%=  @user.errors.messages[:name][0]%>
    <%end%>
    <%= f.label :line_ID%>:        <%= f.text_field :lineID%>
</p>

<p>
    <%= f.submit "変更"%>
</p>
<%end%>

app/views/users/index.html.erb
<h1>ユーザー一覧画面</h1>
<p>
    <ul>
        <% @users.each do |user| %>
            <li>
                <%= link_to user.name,user_path(user.id) %>(lineID:<%=user.lineID%>)
                
            </li>
        <% end %>
    </ul>

</p>
<p>
    <%= link_to 'ユーザー登録画面へ',new_user_path %>
</p>

app/views/users/new.html.erb
<h1>ユーザー登録画面</h1>


<%= form_for @user do |f|%>
<p>
    <%= f.label :新規ユーザー名%>:<%= f.text_field :name%><br>
    <%if @user.errors.any? %>
    <%=  @user.errors.messages[:name][0]%>
    <%end%>
    <%= f.label :line_ID%>:        <%= f.text_field :lineID%>
</p>

<p>
    <%= f.submit%>
</p>
<%end%>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>LINE</title>
        <style media="screen">

        </style>

    </head>
    <body>
        <h1><%=@user.name%></h1>
        <div class="lineid">
            ID:<%= @user.lineID %>
        </div>
        <p>
        <table id="mainmenu">
        	<thead>
        		<tr>
        			<th><%= link_to "プロフィールを編集する",edit_user_path(@user.id) %></th> <th><%= link_to "友達を追加する",new_user_friend_path(@user.id) %>
                    </th> <th><%= link_to "アカウントを削除する",user_path(@user.id),method: :delete,data: {confirm: @user.name+"を本当に削除して良いですか？？"}%></th> <th><%= link_to "ログアウト",users_path %></th>
        		</tr>
        	</thead>
        </table>
        </p>

        <table id="chats">
            <thead>
                <tr>
                <th colspan="3" class="chats">トーク一覧</th>
                </tr>
            </thead>
        	<tbody>
            
                <%@user.chats.each do |chat|%>
        		<tr>
                    <th><%= link_to User.find(chat.send_to_ID).name,user_chat_path(chat.user_id,chat.id) %></th>
                    <% user2=User.find(chat.send_to_ID) %>
                    <% chat2=user2.chats.find_by(send_to_ID: @user.id) %>
                    <% message=chat.messages.last %>
                    <% message2=chat2.messages.last %>
                    <% if message2 != nil && message != nil %>
                        <% if message.created_at > message2.created_at %>
                            <td><%= message.text %></td>
                            <% else %>
                            <td><%= message2.text %></td>
                        <% end %>
                        <% elsif message2 !=nil%>
                        <td><%= message2.text %></td>
                        <% elsif message !=nil%>
                        <td><%= message.text %></td>
                        <% else %>
                        <td></td>
                    <% end %>
                    <td class="delete"><%= link_to "削除する",user_chat_path(chat.user.id,chat.id),method: :delete,data: {confirm: "このトークを本当に削除して良いですか？？"} %></td>
        		</tr>
                <%end%>
        	</tbody>
        </table>


        <table id="friends">
            <thead>
                <tr>
                <th colspan="2" class="friends" >友達一覧</th>
                </tr>
            </thead>
        	<tbody>
                <%@user.friends.each do |friend|%>
        		<tr>
        			<th><%= link_to User.find(friend.friend_id).name,user_friend_path(friend.user_id,friend.id) %></th>
                    <td>ID:<%= User.find(friend.friend_id).lineID %></td>
                </tr>
                <%end%>
        	</tbody>
        </table>




    </body>
</html>